name: 腾讯视频签到

on:
    workflow_dispatch:
    schedule:
        - cron: "30 13 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行【腾讯视频签到】"
              run: |
                  node function/v_video.js
              env:
                  V_REF_URL: https://access.video.qq.com/user/auth_refresh?vappid=11059694&vsecret=fdf61a6be0aad57132bc5cdf78ac30145b6cd2c1470b0cfe&type=qq&g_tk=18172118&g_vstk=982111664&g_actk=&callback=jQuery19108960631941746682_1606467106856&_=1606467106857
                  V_COOKIE: RK=PGxId2tmHp; ptcz=09dc95096c3d59ee3e75a95ad1476eca07de00a300559212688829d40a225c9a; eas_sid=n1i6I0b348D8R2U8W8c4z5m1Y2; pgv_pvid=6759570432; pgv_pvi=9325967360; pgg_uid=149244732; pgg_appid=101503919; pgg_openid=001CECF5BA161FE74B74478A68C99E64; pgg_access_token=B8D9FE021AEF931A54D2BEE87586BC28; pgg_type=1; pgg_user_type=5; uin=o0981210382; skey=@Gdu5ZOYQI; tvfe_boss_uuid=2592d22246b927b6; video_guid=b4c7afb632f15fa2; video_platform=2; main_login=qq; vuserid=546734439; vusession=y2V_bgmEaoQTaVNSEjjh_g..; login_time_init=1606466433; _video_qq_version=1.1; _video_qq_main_login=qq; _video_qq_appid=3000501; _video_qq_vuserid=546734439; _video_qq_vusession=y2V_bgmEaoQTaVNSEjjh_g..; _video_qq_login_time_init=1606466433; pgv_info=ssid=s8538918964; o_cookie=981210382; pgv_si=s8470577152; next_refresh_time=6379; _video_qq_next_refresh_time=6379; login_time_last=2020-11-27 16:44:16
                  SEND_KEY: ${{ secrets.SEND_KEY }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  BARK_SOUND: ${{ secrets.BARK_SOUND }}
                  DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
                  DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
#最后推送 2020年11月20日
