name: 腾讯视频签到

on:
    workflow_dispatch:
    schedule:
        - cron: "30 13 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行【腾讯视频签到】"
              run: |
                  node function/v_video.js
              env:
                  V_REF_URL: https://access.video.qq.com/user/auth_refresh?vappid=11059694&vsecret=fdf61a6be0aad57132bc5cdf78ac30145b6cd2c1470b0cfe&type=qq&g_tk=&g_vstk=1375755387&g_actk=1029548671&callback=jQuery19106582072327332675_1606989000433&_=1606989000434
                  V_COOKIE: RK=PGxId2tmHp; ptcz=09dc95096c3d59ee3e75a95ad1476eca07de00a300559212688829d40a225c9a; eas_sid=n1i6I0b348D8R2U8W8c4z5m1Y2; pgv_pvid=6759570432; pgv_pvi=9325967360; pgg_uid=149244732; pgg_appid=101503919; pgg_openid=001CECF5BA161FE74B74478A68C99E64; pgg_access_token=B8D9FE021AEF931A54D2BEE87586BC28; pgg_type=1; pgg_user_type=5; tvfe_boss_uuid=2592d22246b927b6; video_platform=2; video_guid=b4c7afb632f15fa2; _video_qq_login_time_init=1606466433; o_cookie=981210382; main_login=qq; vqq_access_token=EEA4F3411FE7FB7F6A9D5ECD3EBE0F9B; vqq_appid=101483052; vqq_openid=1DD788C969CFCA13F1D492719C9174C2; vqq_vuserid=546734439; vqq_refresh_token=3C6BD740D3882623FBBBBA04D277FF5B; uid=343086108; vqq_vusession=j___AI4x0UEq7Z8jfE3VJQ..; pgv_info=ssid=s7777412706; vqq_next_refresh_time=6599; vqq_login_time_init=1606988798; login_time_last=2020-12-3 17:46:40
                  SEND_KEY: ${{ secrets.SEND_KEY }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}
                  BARK_SOUND: ${{ secrets.BARK_SOUND }}
                  DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
                  DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
#最后推送 2020年11月20日
